### ISSUE TITLE
Remove tsv/fasta input format

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO#562]
Supporting the legacy input format with tsvs and fastas makes the code in the preprocessing a lot more complicated than it needs to be. We also have some complicated null logic because tsv does not have native support for nulls

**Comment by fengelniederhammer** [comment]
Summary of the recent discussion:
* We want to remove the TSV/FASTA input format.
  * It is essentially unused. All real-world users use the NDJSON input format.
  * The preprocessing code will be a lot easier to maintain, since there will only be one major execution path.
  * NDJSON offers proper handling of null values (TSV requires the workaround of using empty strings)
* We won't do it now
  * If there are any bigger changes in the preprocessing code, then we should first do this issue
    * currently there are none planned.
  * Ideally we can wait until after the Rust experiment:
    * if successful, we can simply delete the C++ part altogether
    * if not successful, we only remove the TSV/FASTA execution path from the C++ code
* We will offer a script / CLI tool to convert the TSV/FASTA input to NDJSON instead.
  * Thus, we still "support" that input format, because it's actually useful. Users are more likely to have TSV and FASTA files instead of NDJSON.
